amzn/smoke-aws

README.md

Currently `README.md` displays code samples without syntax highlighting. This PR fixes that.

Fixed syntax highlighting in README.md

---

Sources/S3Client/S3Object.swift

*Description of changes:* Add the ability to close S3Object.

Add the ability to close S3Object.

---

Package.swift
Sources/RDSClient/AWSRDSClient.swift
Sources/RDSClient/MockRDSClient.swift
Sources/RDSClient/RDSClientProtocol.swift
Sources/RDSClient/RDSOperationsClientInput.swift
Sources/RDSClient/RDSOperationsClientOutput.swift
Sources/RDSClient/ThrowingRDSClient.swift
Sources/RDSModel/RDSModelDefaultInstances.swift
Sources/RDSModel/RDSModelErrors.swift
Sources/RDSModel/RDSModelOperations.swift
Sources/RDSModel/RDSModelStructures.swift
Sources/RDSModel/RDSModelTypes.swift
Tests/RDSClientTests/RDSClientTests.swift

*Issue: https://github.com/amzn/smoke-aws/issues/13
- Added RDS Client and Model by generating code with GO SDK v1.19.27
- Added unit tests (Tests/RDSClientTests)

Add RDS Client

---

Package.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/ElasticContainerClient/AWSElasticContainerClient.swift
Sources/ElasticContainerClient/ElasticContainerClientProtocol.swift
Sources/ElasticContainerClient/ElasticContainerOperationsClientInput.swift
Sources/ElasticContainerClient/ElasticContainerOperationsClientOutput.swift
Sources/ElasticContainerClient/MockElasticContainerClient.swift
Sources/ElasticContainerClient/ThrowingElasticContainerClient.swift
Sources/ElasticContainerModel/ElasticContainerModelDefaultInstances.swift
Sources/ElasticContainerModel/ElasticContainerModelOperations.swift
Sources/ElasticContainerModel/ElasticContainerModelStructures.swift
Sources/ElasticContainerModel/ElasticContainerModelTypes.swift

This change updates `smoke-aws` to the AWS Go SDK v1.20.3 models.

Code generate with Go SDK v1.20.3 models.

---

README.md

Fix CI badge in README for 1.x branch.

---

Package.resolved
Package.swift
Package@swift-5.0.swift
Package@swift-5.1.swift
Sources/CloudWatchModel/CloudWatchModelDefaultInstances.swift
Sources/CloudWatchModel/CloudWatchModelStructures.swift
Sources/CloudWatchModel/CloudWatchModelTypes.swift
Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudClientProtocol.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudInvocationsReporting.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientInput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientOutput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsReporting.swift
Sources/ElasticComputeCloudClient/MockElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ThrowingElasticComputeCloudClient.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelOperations.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/ElasticContainerModel/ElasticContainerModelDefaultInstances.swift
Sources/ElasticContainerModel/ElasticContainerModelStructures.swift
Sources/ElasticContainerModel/ElasticContainerModelTypes.swift
Sources/RDSModel/RDSModelStructures.swift

Code generate with Go SDK v1.30.7 models.

---

Sources/CloudWatchClient/AWSCloudWatchClient.swift
Sources/CloudWatchClient/AWSCloudWatchClientGenerator.swift
Sources/DynamoDBClient/AWSDynamoDBClient.swift
Sources/DynamoDBClient/AWSDynamoDBClientGenerator.swift
Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClientGenerator.swift
Sources/ElasticContainerClient/AWSElasticContainerClient.swift
Sources/ElasticContainerClient/AWSElasticContainerClientGenerator.swift
Sources/RDSClient/AWSRDSClient.swift
Sources/RDSClient/AWSRDSClientGenerator.swift
Sources/RDSDataClient/AWSRDSDataClient.swift
Sources/RDSDataClient/AWSRDSDataClientGenerator.swift
Sources/S3Client/AWSS3Client.swift
Sources/S3Client/AWSS3ClientGenerator.swift
Sources/SecurityTokenClient/AWSSecurityTokenClient.swift
Sources/SecurityTokenClient/AWSSecurityTokenClientGenerator.swift
Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
Sources/SimpleNotificationClient/AWSSimpleNotificationClientGenerator.swift
Sources/SimpleQueueClient/AWSSimpleQueueClient.swift
Sources/SimpleQueueClient/AWSSimpleQueueClientGenerator.swift
Sources/SimpleWorkflowClient/AWSSimpleWorkflowClient.swift
Sources/SimpleWorkflowClient/AWSSimpleWorkflowClientGenerator.swift
Sources/SmokeAWSHttp/DataAWSHttpClientDelegate.swift
Sources/StepFunctionsClient/AWSStepFunctionsClient.swift
Sources/StepFunctionsClient/AWSStepFunctionsClientGenerator.swift

*Description of changes:* Clients to only close httpclients if they created them.

Clients to only close httpclients if they created them.

---

Sources/CloudWatchModel/CloudWatchModelDefaultInstances.swift
Sources/CloudWatchModel/CloudWatchModelStructures.swift
Sources/CloudWatchModel/CloudWatchModelTypes.swift
Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudClientProtocol.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientInput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientOutput.swift
Sources/ElasticComputeCloudClient/MockElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ThrowingElasticComputeCloudClient.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelOperations.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/ElasticContainerModel/ElasticContainerModelDefaultInstances.swift
Sources/ElasticContainerModel/ElasticContainerModelStructures.swift
Sources/ElasticContainerModel/ElasticContainerModelTypes.swift
Sources/RDSClient/AWSRDSClient.swift
Sources/RDSClient/MockRDSClient.swift
Sources/RDSClient/RDSClientProtocol.swift
Sources/RDSClient/ThrowingRDSClient.swift
Sources/RDSModel/RDSModelDefaultInstances.swift
Sources/RDSModel/RDSModelStructures.swift
Sources/RDSModel/RDSModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.30.22 models.

Code generate with Go SDK v1.30.22 models.

---

Package.resolved
Package.swift
Package@swift-5.0.swift
Package@swift-5.1.swift
Sources/CloudformationClient/AWSCloudformationClient.swift
Sources/CloudformationClient/AWSCloudformationClientGenerator.swift
Sources/CloudformationClient/CloudformationClientProtocol.swift
Sources/CloudformationClient/CloudformationInvocationsReporting.swift
Sources/CloudformationClient/CloudformationOperationsClientInput.swift
Sources/CloudformationClient/CloudformationOperationsClientOutput.swift
Sources/CloudformationClient/CloudformationOperationsReporting.swift
Sources/CloudformationClient/MockCloudformationClient.swift
Sources/CloudformationClient/ThrowingCloudformationClient.swift
Sources/CloudformationModel/CloudformationModelDefaultInstances.swift
Sources/CloudformationModel/CloudformationModelErrors.swift
Sources/CloudformationModel/CloudformationModelOperations.swift
Sources/CloudformationModel/CloudformationModelStructures.swift
Sources/CloudformationModel/CloudformationModelTypes.swift
Sources/SmokeAWSHttp/XMLAWSHttpClientDelegate.swift

*Description of changes:* Add model and client for Cloudformation service.

Add model and client for Cloudformation service.

---

Sources/SmokeAWSHttp/AWSClientInvocationTraceContext.swift

1. Log basic outgoing request log line at info
2. Log outgoing body at info
3. Log 400 response log line at warning rather than warning

Improved trace logging

---

Sources/SmokeAWSHttp/AWSClientInvocationTraceContext.swift

Add error log in AWSClientInvocationTraceContext

---

Package.resolved
Sources/CloudformationModel/CloudformationModelDefaultInstances.swift
Sources/CloudformationModel/CloudformationModelStructures.swift
Sources/CloudformationModel/CloudformationModelTypes.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/ElasticContainerModel/ElasticContainerModelDefaultInstances.swift
Sources/ElasticContainerModel/ElasticContainerModelStructures.swift
Sources/ElasticContainerModel/ElasticContainerModelTypes.swift
Sources/S3Client/S3OperationsClientInput.swift
Sources/S3Model/S3ModelDefaultInstances.swift
Sources/S3Model/S3ModelOperations.swift
Sources/S3Model/S3ModelStructures.swift

Code generate with Go SDK v1.31.10 models.

---

Sources/CloudWatchModel/CloudWatchModelDefaultInstances.swift
Sources/CloudWatchModel/CloudWatchModelStructures.swift
Sources/CloudWatchModel/CloudWatchModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.37.1 models.

Code generate with Go SDK v1.37.1 models.

---

Sources/CloudformationModel/CloudformationModelDefaultInstances.swift
Sources/CloudformationModel/CloudformationModelStructures.swift
Sources/CloudformationModel/CloudformationModelTypes.swift
Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudClientProtocol.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudInvocationsReporting.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientInput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientOutput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsReporting.swift
Sources/ElasticComputeCloudClient/MockElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ThrowingElasticComputeCloudClient.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelOperations.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/RDSClient/AWSRDSClient.swift
Sources/RDSClient/MockRDSClient.swift
Sources/RDSClient/RDSClientProtocol.swift
Sources/RDSClient/RDSInvocationsReporting.swift
Sources/RDSClient/RDSOperationsClientInput.swift
Sources/RDSClient/RDSOperationsClientOutput.swift
Sources/RDSClient/RDSOperationsReporting.swift
Sources/RDSClient/ThrowingRDSClient.swift
Sources/RDSDataModel/RDSDataModelTypes.swift
Sources/RDSModel/RDSModelDefaultInstances.swift
Sources/RDSModel/RDSModelOperations.swift
Sources/RDSModel/RDSModelStructures.swift
Sources/RDSModel/RDSModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.37.15 models.

Code generate with Go SDK v1.37.15 models.

---

Package.swift
Package@swift-5.1.swift
Sources/ECRClient/AWSECRClient.swift
Sources/ECRClient/AWSECRClientGenerator.swift
Sources/ECRClient/ECRClientProtocol.swift
Sources/ECRClient/ECRInvocationsReporting.swift
Sources/ECRClient/ECROperationsClientInput.swift
Sources/ECRClient/ECROperationsClientOutput.swift
Sources/ECRClient/ECROperationsReporting.swift
Sources/ECRClient/MockECRClient.swift
Sources/ECRClient/ThrowingECRClient.swift
Sources/ECRModel/ECRModelDefaultInstances.swift
Sources/ECRModel/ECRModelErrors.swift
Sources/ECRModel/ECRModelOperations.swift
Sources/ECRModel/ECRModelStructures.swift
Sources/ECRModel/ECRModelTypes.swift
Sources/S3Model/S3ModelDefaultInstances.swift
Sources/S3Model/S3ModelOperations.swift
Sources/S3Model/S3ModelStructures.swift

*Description of changes:* Code generate with Go SDK v1.37.22 models.

Code generate with Go SDK v1.37.22 models.

---

Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/ElasticContainerClient/AWSElasticContainerClient.swift
Sources/ElasticContainerClient/ElasticContainerClientProtocol.swift
Sources/ElasticContainerClient/ElasticContainerInvocationsReporting.swift
Sources/ElasticContainerClient/ElasticContainerOperationsClientInput.swift
Sources/ElasticContainerClient/ElasticContainerOperationsClientOutput.swift
Sources/ElasticContainerClient/ElasticContainerOperationsReporting.swift
Sources/ElasticContainerClient/MockElasticContainerClient.swift
Sources/ElasticContainerClient/ThrowingElasticContainerClient.swift
Sources/ElasticContainerModel/ElasticContainerModelDefaultInstances.swift
Sources/ElasticContainerModel/ElasticContainerModelErrors.swift
Sources/ElasticContainerModel/ElasticContainerModelOperations.swift
Sources/ElasticContainerModel/ElasticContainerModelStructures.swift
Sources/ElasticContainerModel/ElasticContainerModelTypes.swift
Sources/S3Client/AWSS3Client.swift
Sources/S3Client/MockS3Client.swift
Sources/S3Client/S3ClientProtocol.swift
Sources/S3Client/S3InvocationsReporting.swift
Sources/S3Client/S3OperationsClientInput.swift
Sources/S3Client/S3OperationsReporting.swift
Sources/S3Client/ThrowingS3Client.swift
Sources/S3Model/S3ModelDefaultInstances.swift
Sources/S3Model/S3ModelOperations.swift
Sources/S3Model/S3ModelStructures.swift
Sources/S3Model/S3ModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.38.5 models.

Code generate with Go SDK v1.38.5 models.

---

Sources/CloudWatchClient/AWSCloudWatchClient.swift
Sources/CloudWatchClient/CloudWatchClientProtocol.swift
Sources/CloudWatchClient/CloudWatchInvocationsReporting.swift
Sources/CloudWatchClient/CloudWatchOperationsClientInput.swift
Sources/CloudWatchClient/CloudWatchOperationsClientOutput.swift
Sources/CloudWatchClient/CloudWatchOperationsReporting.swift
Sources/CloudWatchClient/MockCloudWatchClient.swift
Sources/CloudWatchClient/ThrowingCloudWatchClient.swift
Sources/CloudWatchModel/CloudWatchModelDefaultInstances.swift
Sources/CloudWatchModel/CloudWatchModelOperations.swift
Sources/CloudWatchModel/CloudWatchModelStructures.swift
Sources/CloudWatchModel/CloudWatchModelTypes.swift
Sources/CloudformationModel/CloudformationModelDefaultInstances.swift
Sources/CloudformationModel/CloudformationModelStructures.swift
Sources/CloudformationModel/CloudformationModelTypes.swift
Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudClientProtocol.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudInvocationsReporting.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientInput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientOutput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsReporting.swift
Sources/ElasticComputeCloudClient/MockElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ThrowingElasticComputeCloudClient.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelOperations.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/SecurityTokenModel/SecurityTokenModelDefaultInstances.swift
Sources/SecurityTokenModel/SecurityTokenModelStructures.swift
Sources/SecurityTokenModel/SecurityTokenModelTypes.swift

Code generate with Go SDK v1.38.25 models.

Code generate with Go SDK v1.38.25 models.

---

.travis.yml
Package.resolved

*Description of changes:* Add CI for Swift 5.4.

Add CI for Swift 5.4.

---

Package.swift

*Description of changes:* Align watchOS platform with dependency requirements.

Align watchOS platform with dependency requirements.

---

.travis.yml
Package.resolved
Package.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/ElasticContainerModel/ElasticContainerModelTypes.swift
Sources/S3Model/S3ModelTypes.swift
Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
Sources/SimpleNotificationClient/MockSimpleNotificationClient.swift
Sources/SimpleNotificationClient/SimpleNotificationClientProtocol.swift
Sources/SimpleNotificationClient/SimpleNotificationInvocationsReporting.swift
Sources/SimpleNotificationClient/SimpleNotificationOperationsClientInput.swift
Sources/SimpleNotificationClient/SimpleNotificationOperationsClientOutput.swift
Sources/SimpleNotificationClient/SimpleNotificationOperationsReporting.swift
Sources/SimpleNotificationClient/ThrowingSimpleNotificationClient.swift
Sources/SimpleNotificationModel/SimpleNotificationModelDefaultInstances.swift
Sources/SimpleNotificationModel/SimpleNotificationModelErrors.swift
Sources/SimpleNotificationModel/SimpleNotificationModelOperations.swift
Sources/SimpleNotificationModel/SimpleNotificationModelStructures.swift
Sources/SimpleNotificationModel/SimpleNotificationModelTypes.swift
Sources/_SmokeAWSHttpConcurrency/AWSClientProtocol.swift
Sources/_SmokeAWSHttpConcurrency/AWSQueryClientProtocol.swift

*Description of changes:* Code generate with Go SDK v1.38.57 models.

Code generate with Go SDK v1.38.57 models.

---

Sources/CloudformationClient/AWSCloudformationClient.swift
Sources/CloudformationClient/CloudformationClientProtocol.swift
Sources/CloudformationClient/CloudformationInvocationsReporting.swift
Sources/CloudformationClient/CloudformationOperationsClientInput.swift
Sources/CloudformationClient/CloudformationOperationsClientOutput.swift
Sources/CloudformationClient/CloudformationOperationsReporting.swift
Sources/CloudformationClient/MockCloudformationClient.swift
Sources/CloudformationClient/ThrowingCloudformationClient.swift
Sources/CloudformationModel/CloudformationModelDefaultInstances.swift
Sources/CloudformationModel/CloudformationModelErrors.swift
Sources/CloudformationModel/CloudformationModelOperations.swift
Sources/CloudformationModel/CloudformationModelStructures.swift
Sources/CloudformationModel/CloudformationModelTypes.swift
Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudClientProtocol.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudInvocationsReporting.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientInput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientOutput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsReporting.swift
Sources/ElasticComputeCloudClient/MockElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ThrowingElasticComputeCloudClient.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelOperations.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/RDSModel/RDSModelDefaultInstances.swift
Sources/RDSModel/RDSModelStructures.swift
Sources/RDSModel/RDSModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.39.0 models.

Code generate with Go SDK v1.39.0 models.

---

Sources/CodePipelineModel/CodePipelineModelDefaultInstances.swift
Sources/CodePipelineModel/CodePipelineModelTypes.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.40.26 models.

Code generate with Go SDK v1.40.26 models.

---

Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/RDSModel/RDSModelDefaultInstances.swift
Sources/RDSModel/RDSModelStructures.swift
Sources/S3Model/S3ModelDefaultInstances.swift
Sources/S3Model/S3ModelStructures.swift
Sources/S3Model/S3ModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.40.44 models.

Code generate with Go SDK v1.40.44 models.

---

Sources/CodePipelineModel/CodePipelineModelErrors.swift
Sources/DynamoDBModel/DynamoDBModelErrors.swift
Sources/ECRModel/ECRModelErrors.swift
Sources/ElasticContainerModel/ElasticContainerModelErrors.swift
Sources/RDSDataModel/RDSDataModelErrors.swift
Sources/SimpleWorkflowModel/SimpleWorkflowModelErrors.swift
Sources/SmokeAWSHttp/AWSClientInvocationTraceContext.swift
Sources/StepFunctionsModel/StepFunctionsModelErrors.swift

1. Handle JSON errors where the type isn't specified. 
2. Add ability to disable request trace logging.

Handle JSON errors where the type isn't specified. 

---

Sources/ECRClient/AWSECRClient.swift
Sources/ECRClient/ECRClientProtocol.swift
Sources/ECRClient/ECRInvocationsReporting.swift
Sources/ECRClient/ECROperationsClientInput.swift
Sources/ECRClient/ECROperationsClientOutput.swift
Sources/ECRClient/ECROperationsReporting.swift
Sources/ECRClient/MockECRClient.swift
Sources/ECRClient/ThrowingECRClient.swift
Sources/ECRModel/ECRModelDefaultInstances.swift
Sources/ECRModel/ECRModelOperations.swift
Sources/ECRModel/ECRModelStructures.swift
Sources/ECRModel/ECRModelTypes.swift
Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudClientProtocol.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudInvocationsReporting.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientInput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientOutput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsReporting.swift
Sources/ElasticComputeCloudClient/MockElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ThrowingElasticComputeCloudClient.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelOperations.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
docs/Support_Policy.md

*Description of changes:* Code generate with Go SDK v1.41.0 models.

Code generate with Go SDK v1.41.0 models.

---

Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.41.5 models.

Code generate with Go SDK v1.41.5 models.

---

Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudClientProtocol.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudInvocationsReporting.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientInput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsClientOutput.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudOperationsReporting.swift
Sources/ElasticComputeCloudClient/MockElasticComputeCloudClient.swift
Sources/ElasticComputeCloudClient/ThrowingElasticComputeCloudClient.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelOperations.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
Sources/ElasticContainerModel/ElasticContainerModelDefaultInstances.swift
Sources/ElasticContainerModel/ElasticContainerModelStructures.swift
Sources/ElasticContainerModel/ElasticContainerModelTypes.swift
Sources/RDSClient/AWSRDSClient.swift
Sources/RDSClient/MockRDSClient.swift
Sources/RDSClient/RDSClientProtocol.swift
Sources/RDSClient/RDSInvocationsReporting.swift
Sources/RDSClient/RDSOperationsClientInput.swift
Sources/RDSClient/RDSOperationsClientOutput.swift
Sources/RDSClient/RDSOperationsReporting.swift
Sources/RDSClient/ThrowingRDSClient.swift
Sources/RDSModel/RDSModelDefaultInstances.swift
Sources/RDSModel/RDSModelErrors.swift
Sources/RDSModel/RDSModelOperations.swift
Sources/RDSModel/RDSModelStructures.swift
Sources/RDSModel/RDSModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.41.17 models.

Code generate with Go SDK v1.41.17 models.

---

Sources/ElasticContainerModel/ElasticContainerModelTypes.swift

Code generate with Go SDK v1.42.44 models.

Code generate with Go SDK v1.42.44 models.

---

Sources/DynamoDBClient/AWSDynamoDBClient.swift

Retry DynamoDB on internalServer errors.

Retry DynamoDB on internalServer errors.

---

Sources/SmokeAWSHttp/AWSClientInvocationTraceContext.swift

*Description of changes:* Add option to log 4XX responses at ERROR.

Add option to log 4XX responses at ERROR.

---

Sources/AppConfigClient/AWSAppConfigClient.swift
Sources/AppConfigClient/AppConfigClientProtocol+async.swift
Sources/AppConfigClient/AppConfigClientProtocol.swift
Sources/AppConfigClient/AppConfigInvocationsReporting.swift
Sources/AppConfigClient/AppConfigOperationsClientInput.swift
Sources/AppConfigClient/AppConfigOperationsClientOutput.swift
Sources/AppConfigClient/AppConfigOperationsReporting.swift
Sources/AppConfigClient/MockAppConfigClient.swift
Sources/AppConfigClient/ThrowingAppConfigClient.swift
Sources/AppConfigModel/AppConfigModelDefaultInstances.swift
Sources/AppConfigModel/AppConfigModelOperations.swift
Sources/AppConfigModel/AppConfigModelStructures.swift
Sources/AppConfigModel/AppConfigModelTypes.swift
Sources/CloudformationModel/CloudformationModelDefaultInstances.swift
Sources/CloudformationModel/CloudformationModelStructures.swift
Sources/CloudformationModel/CloudformationModelTypes.swift
Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
Sources/SimpleNotificationClient/AWSSimpleNotificationClientGenerator.swift

*Description of changes:* Code generate with Go SDK v1.44.59 models.

Code generate with Go SDK v1.44.59 models.

---

Sources/CloudWatchModel/CloudWatchModelDefaultInstances.swift
Sources/CloudWatchModel/CloudWatchModelStructures.swift
Sources/CloudWatchModel/CloudWatchModelTypes.swift
Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
Sources/SimpleNotificationClient/AWSSimpleNotificationClientGenerator.swift

1. Code generate with Go SDK v1.44.60 models.
2. Restore the change for large SNS payloads

Code generate with Go SDK v1.44.60 models.

---

Package.resolved
Package.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift

*Description of changes:* Code generate with Go SDK v1.44.114 models.

Code generate with Go SDK v1.44.114 models.

---

Sources/AppConfigClient/AppConfigClientProtocol+async.swift
Sources/CloudWatchClient/CloudWatchClientProtocol+async.swift
Sources/CloudformationClient/CloudformationClientProtocol+async.swift
Sources/CodePipelineClient/CodePipelineClientProtocol+async.swift
Sources/DynamoDBClient/DynamoDBClientProtocol+async.swift
Sources/ECRClient/ECRClientProtocol+async.swift
Sources/ElasticComputeCloudClient/ElasticComputeCloudClientProtocol+async.swift
Sources/ElasticContainerClient/ElasticContainerClientProtocol+async.swift
Sources/RDSClient/RDSClientProtocol+async.swift
Sources/RDSDataClient/RDSDataClientProtocol+async.swift
Sources/S3Client/S3ClientProtocol+async.swift
Sources/SecurityTokenClient/SecurityTokenClientProtocol+async.swift
Sources/SimpleNotificationClient/SimpleNotificationClientProtocol+async.swift
Sources/SimpleQueueClient/SimpleQueueClientProtocol+async.swift
Sources/SimpleWorkflowClient/SimpleWorkflowClientProtocol+async.swift
Sources/SmokeAWSMetrics/CloudWatchPendingMetricsQueue.swift
Sources/StepFunctionsClient/StepFunctionsClientProtocol+async.swift

*Description of changes:* Use checked continuations rather than unsafe ones. Checked ones will error if continuation isn't actually used.

Use checked continuations.

---

.github/workflows/swift.yml
README.md
docs/Support_Policy.md

*Description of changes:* Add CI for 5.8, drop for 5.5.

Add CI for 5.8, drop for 5.5.

---

.github/workflows/codeql.yml
Package.resolved

*Description of changes:* Update dependencies and add CodeQL.

Update dependencies and add CodeQL.
