amzn/smoke-aws

- Package.resolved
- Sources/S3Client/S3Object.swift
- Sources/S3Client/String+asS3ObjectIdentifier.swift
- Tests/S3ClientTests/S3ClientTests.swift
*Description of changes:* Enhance String.asS3ObjectIdentifier() to be able to parse http and https S3 urls. Drop the leading "/" from the key returned from this function to be compatible with the AWSS3Client. Add logic to add back the leading "/" on they key in the S3Object client.
> String.asS3ObjectIdentifier() to parse http and http S3 urls

- Package.resolved
- Package.swift
- Sources/CloudWatchClient/AWSCloudWatchClient.swift
- Sources/DynamoDBClient/AWSDynamoDBClient.swift
- Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
- Sources/ElasticContainerClient/AWSElasticContainerClient.swift
- Sources/S3Client/AWSS3Client.swift
- Sources/SecurityTokenClient/AWSSecurityTokenClient.swift
- Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
- Sources/SimpleQueueClient/AWSSimpleQueueClient.swift
- Sources/SimpleWorkflowClient/AWSSimpleWorkflowClient.swift
- Sources/StepFunctionsClient/AWSStepFunctionsClient.swift
*Description of changes:* Move all AWS clients to retriable entry points of HTTPClient. This allows all AWS clients to take advantage of automatic retries with exponential backoff. By default, all AWS clients use the default retry configuration with the ability to override this in the client's initialiser.
All these changes are the result of code generation but I think it is worth while to review the added logic manually.
> Move all AWS clients to retriable entry points of HTTPClient.

- Sources/SmokeAWSHttp/String+hmac.swift
*Description of changes:* Identified a memory leak in hmac generation with the Xcode Memory Graph Debugger. The same fix has been applied to similar code in aws-sdk-swift-core[1].
*Testing performed:* Re-ran Xcode Memory Graph Debugger with fix, showing no memory issue.
[1] https://github.com/swift-aws/aws-sdk-swift-core/commit/6a4a7e07364934f31052f895490eb1dd5a277eea
> Fix memory leak in hmac generation.

- Package.resolved
- Package.swift
- Sources/CloudWatchModel/CloudWatchModelErrors.swift
- Sources/DynamoDBModel/DynamoDBModelErrors.swift
- Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
- Sources/ElasticComputeCloudModel/ElasticComputeCloudModelErrors.swift
- Sources/ElasticContainerModel/ElasticContainerModelErrors.swift
- Sources/S3Model/S3ModelErrors.swift
- Sources/SecurityTokenModel/SecurityTokenModelErrors.swift
- Sources/SimpleNotificationModel/SimpleNotificationModelErrors.swift
- Sources/SimpleNotificationModel/SimpleNotificationModelStructures.swift
- Sources/SimpleQueueModel/SimpleQueueModelErrors.swift
- Sources/SimpleWorkflowModel/SimpleWorkflowModelErrors.swift
- Sources/SmokeAWSHttp/AWSClientChannelInboundHandlerDelegate.swift
- Sources/SmokeAWSHttp/DataAWSHttpClientDelegate.swift
- Sources/SmokeAWSHttp/XMLAWSHttpClientDelegate.swift
- Sources/StepFunctionsModel/StepFunctionsModelErrors.swift
- Tests/ElasticComputeCloudClientTests/ElasticComputeCloudClientTests.swift
- Tests/S3ClientTests/S3ClientTests.swift
- Tests/SecurityTokenClientTests/SecurityTokenClientTests.swift
- Tests/SimpleNotificationClientTests/SimpleNotificationClientTests.swift
- Tests/SimpleQueueClientTests/SimpleQueueClientTests.swift
*Issue #, if available:* #10 
* Correctly use error codes as specified in some service models
* Add an accessDenied error case as this is returned by some services
* capitalise the first character of query keys of ec2 requests as this appears to be required without being modelled 
* take EC2 errors from the documentation as they don't seem to be modelled
* correctly decode errors returned from EC2
* add unit tests to verify we are decoding errors from these services correctly.
*Testing performed:* Added unit tests. Manually verified calling these services to verify the XML returned and that they were parsed correctly.
> Fix error parsing for query services. Capitalize query keys for EC2.

- Sources/CloudWatchClient/AWSCloudWatchClient.swift
- Sources/DynamoDBClient/AWSDynamoDBClient.swift
- Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
- Sources/ElasticContainerClient/AWSElasticContainerClient.swift
- Sources/S3Client/AWSS3Client.swift
- Sources/SecurityTokenClient/AWSSecurityTokenClient.swift
- Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
- Sources/SimpleQueueClient/AWSSimpleQueueClient.swift
- Sources/SimpleWorkflowClient/AWSSimpleWorkflowClient.swift
- Sources/SmokeAWSCore/JSONDecoder+awsCompatibleDecoder.swift
- Sources/SmokeAWSCore/JSONDecoder+awsCompatibleEncoder.swift
- Sources/SmokeAWSCore/XMLDecoder+awsCompatibleDecoder.swift
- Sources/SmokeAWSCore/XMLEncoder+awsCompatibleEncoder.swift
- Sources/SmokeAWSHttp/DataAWSHttpClientDelegate.swift
- Sources/SmokeAWSHttp/JSONAWSHttpClientDelegate.swift
- Sources/SmokeAWSHttp/V4Signer.swift
- Sources/SmokeAWSHttp/XMLAWSHttpClientDelegate.swift
- Sources/StepFunctionsClient/AWSStepFunctionsClient.swift
* Add the ability to pass an eventLoopProvider into each client, allowing clients to share the same event loop threads.
* Avoid `localizedCompare` as this can have issues with thread pools (using thread local storage)
* Avoid using singleton decoder and encoder as these might store memory.
*Testing performed:* Tested in beta environment (Linux). Confirmed functionally correct. Continuing to investigate long term memory performance.
> Add the ability to pass an eventLoopProvider into each client

- Package.resolved
- Sources/SmokeAWSHttp/XMLAWSHttpClientDelegate.swift
N/A
This change removes the single quote character `\'` from the `CharacterSet` of allowed characters in the query portion of AWS request URIs.
I have tested this change for several different AWS services locally.
> Remove single quote from set of allowed query characters

- .gitignore
- Sources/SmokeAWSHttp/XMLAWSHttpClientDelegate.swift
*Description of changes:* These characters break SNS publish requests. Verified SNS publish request with payload ",'.|():{_=-}~!*&()-._&$,&@%-.0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"
> Remove '&', '(' and ')' from the uriAWSQueryValueAllowed character set.

- .travis.yml
- CITests/run
- Package.resolved
- Package.swift
- README.md
- Sources/SmokeAWSHttp/String+hmac.swift
- Sources/SmokeAWSHttp/sha256Extensions.swift
*Issue #, if available:* #14 #25 
1. Use BlueCryptor to support systems that ship with OpenSSL 1.1.
2. Require 0.4.1 of XMLCoding dependency to support Swift 5.1.
3. Add Swift 5.0 and 5.1 CI Tests for both Ubuntu 16.04 and 18.04
> Swift 5.x and Ubuntu 18.04 compatibility

- .travis.yml
- CITests/run
- Package.resolved
- Package.swift
- README.md
*Issue #, if available:* #25 
1. Require 0.4.1 of XMLCoding dependency to support Swift 5.1.
2. Add Swift 5.0 and 5.1 CI Tests for Ubuntu 16.04
> Add CI tests for Swift 5.0 and 5.1 (1.x branch).

- Package.swift
XMLDecode/Encoder uses .iso8601 that is available starting iOS10
> Xcode-11 compatible platforms: macOS10.12, iOS10

- Package.resolved
- Package.swift
*Description of changes:* Use valid semantic version for SmokeHTTP.
> Use valid semantic version for SmokeHTTP.

- Sources/SmokeAWSCore/MockInvocationReporting.swift
- Tests/ElasticComputeCloudClientTests/ElasticComputeCloudClientTests.swift
- Tests/RDSClientTests/RDSClientTests.swift
- Tests/S3ClientTests/S3ClientTests.swift
- Tests/SecurityTokenClientTests/SecurityTokenClientTests.swift
- Tests/SimpleNotificationClientTests/SimpleNotificationClientTests.swift
- Tests/SimpleQueueClientTests/SimpleQueueClientTests.swift
1. Add a MockInvocationReporting type, for testing. 
2. Use the MockInvocationTraceContext provided by SmokeHTTP.
> Add a MockInvocationReporting type, for testing. 

- Sources/CloudWatchClient/AWSCloudWatchClient.swift
- Sources/DynamoDBClient/AWSDynamoDBClient.swift
- Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
- Sources/ElasticContainerClient/AWSElasticContainerClient.swift
- Sources/RDSClient/AWSRDSClient.swift
- Sources/RDSDataClient/AWSRDSDataClient.swift
- Sources/S3Client/AWSS3Client.swift
- Sources/SecurityTokenClient/AWSSecurityTokenClient.swift
- Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
- Sources/SimpleQueueClient/AWSSimpleQueueClient.swift
- Sources/SimpleWorkflowClient/AWSSimpleWorkflowClient.swift
- Sources/SmokeAWSHttp/ConvertableError.swift
- Sources/SmokeAWSHttp/HTTPOperationsClient+executeOperations.swift
- Sources/StepFunctionsClient/AWSStepFunctionsClient.swift
*Issue #, if available:* #55 
*Description of changes:* 
1. Throw the correct typed error from *Sync APIs
2. Refactor code to avoid defining the innerCompletion handler for each api.
*Testing performed:* Verified correct error was thrown from the sync APIs. 
> Fix thrown error type from sync APIs.

- Package.resolved
- Sources/CloudWatchClient/AWSCloudWatchClient.swift
- Sources/CloudWatchClient/AWSCloudWatchClientGenerator.swift
This change adds the necessary list encoding & decoding strategies for the Cloudwatch client.
> Add listEncodingStrategy for Cloudwatch client

- Package.resolved
- Sources/ElasticComputeCloudModel/ElasticComputeCloudModelDefaultInstances.swift
- Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
- Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
*Description of changes:* Code generate with Go SDK v1.30.28 models.
> Code generate with Go SDK v1.30.28 models.

- Package.swift
- Package@swift-5.1.swift
- Sources/CloudWatchClient/AWSCloudWatchClient.swift
- Sources/CloudWatchClient/AWSCloudWatchClientGenerator.swift
- Sources/CloudformationClient/AWSCloudformationClient.swift
- Sources/CloudformationClient/AWSCloudformationClientGenerator.swift
- Sources/DynamoDBClient/AWSDynamoDBClient.swift
- Sources/DynamoDBClient/AWSDynamoDBClientGenerator.swift
- Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
- Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClientGenerator.swift
- Sources/ElasticContainerClient/AWSElasticContainerClient.swift
- Sources/ElasticContainerClient/AWSElasticContainerClientGenerator.swift
- Sources/RDSClient/AWSRDSClient.swift
- Sources/RDSClient/AWSRDSClientGenerator.swift
- Sources/RDSDataClient/AWSRDSDataClient.swift
- Sources/RDSDataClient/AWSRDSDataClientGenerator.swift
- Sources/S3Client/AWSS3Client.swift
- Sources/S3Client/AWSS3ClientGenerator.swift
- Sources/SecurityTokenClient/AWSSecurityTokenClient.swift
- Sources/SecurityTokenClient/AWSSecurityTokenClientGenerator.swift
- Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
- Sources/SimpleNotificationClient/AWSSimpleNotificationClientGenerator.swift
- Sources/SimpleQueueClient/AWSSimpleQueueClient.swift
- Sources/SimpleQueueClient/AWSSimpleQueueClientGenerator.swift
- Sources/SimpleWorkflowClient/AWSSimpleWorkflowClient.swift
- Sources/SimpleWorkflowClient/AWSSimpleWorkflowClientGenerator.swift
- Sources/StepFunctionsClient/AWSStepFunctionsClient.swift
- Sources/StepFunctionsClient/AWSStepFunctionsClientGenerator.swift
1. Fix an error were the error type check was being performed on the HTTPClientError instance (and failing) rather that the client error cause. This was causing requests to be retried in error.
2. Change the fallback retry behaviour to depend on the http response code - 400s are not retried, other errors are retried.
> Use http response code for fallback retry behaviour.

- Package.resolved
- Package.swift
- Package@swift-5.1.swift
- Sources/SmokeAWSCore/SmokeAWSClientReportingConfiguration.swift
- Sources/SmokeAWSHttp/SmokeAWSHTTPClientInvocationReporting.swift
- Sources/SmokeAWSMetrics/CloudWatchCounterHandler.swift
- Sources/SmokeAWSMetrics/CloudWatchMetricsFactory.swift
- Sources/SmokeAWSMetrics/CloudWatchRecorderHandler.swift
- Sources/SmokeAWSMetrics/CloudWatchTimerHandler.swift
1. Add swift-metrics implementation for CloudWatch. 
2. Support aggregating info about output requests.
> Add swift-metrics implementation for CloudWatch.

- Sources/SmokeAWSMetrics/CloudWatchCounterHandler.swift
- Sources/SmokeAWSMetrics/CloudWatchMetricsFactory.swift
- Sources/SmokeAWSMetrics/CloudWatchPendingMetricsQueue.swift
- Sources/SmokeAWSMetrics/CloudWatchRecorderHandler.swift
- Sources/SmokeAWSMetrics/CloudWatchTimerHandler.swift
*Description of changes:* To reduce the calls being made to the CloudWatch service, serialise all metrics received into a queue that is drained at a regular interval (2 seconds) with metrics in the same namespace being combined into a single CloudWatch call (up to a maximum of 100 metric payloads per call).
Also cleaned up some access controls; only `CloudWatchMetricsFactory` needs to be public.
> Use a queue to submit metrics to CloudWatch at regular intervals.

- .travis.yml
- Package.resolved
- Package.swift
- Package@swift-5.1.swift
- README.md
- Sources/SmokeAWSCore/SmokeAWSClientReportingConfiguration.swift
- Sources/_SmokeAWSHttpConcurrency/AWSClientProtocol.swift
- Sources/_SmokeAWSHttpConcurrency/AWSQueryClientProtocol.swift
- docs/Support_Policy.md
1. Add experimental async/await support. This doesn't yet add support to the generated clients in this package but will allow other generated clients to test out async/await support.
2. Add details to the README on how to configure the reporting configuration for clients.
> Experimental async/await support. ReportingConfiguration documentation. 

- Sources/CloudformationModel/CloudformationModelDefaultInstances.swift
- Sources/CloudformationModel/CloudformationModelStructures.swift
- Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift
- Sources/ElasticComputeCloudModel/ElasticComputeCloudModelTypes.swift
- Sources/ElasticContainerModel/ElasticContainerModelDefaultInstances.swift
- Sources/ElasticContainerModel/ElasticContainerModelStructures.swift
- docs/Support_Policy.md
*Description of changes:* Code generate with Go SDK v1.38.40 models.
> Code generate with Go SDK v1.38.40 models.

- Sources/SmokeAWSHttp/MockClientProtocol.swift
- Sources/SmokeAWSHttp/MockThrowingClientProtocol.swift
- Sources/_SmokeAWSHttpConcurrency/MockClientProtocol.swift
- Sources/_SmokeAWSHttpConcurrency/MockThrowingClientProtocol.swift
*Description of changes:* Do not create promises when they wont be used; when the `EventLoopFuture`-returning implementation override is returned. This will cause a fatal error when debugging[1].
[1] https://github.com/apple/swift-nio/blob/main/Sources/NIOCore/EventLoopFuture.swift#L420
> Do not create promises when they wont be used.

- Sources/S3Client/String+asS3ObjectIdentifier.swift
- Tests/S3ClientTests/S3ClientTests.swift
Virtual hosted style S3 URLs are in this format: https://bucket.s3.amazonaws.com/key
String.asS3ObjectIdentifier() now supports http and https URLs in the path style and the virtual hosted style, in addition to s3:// URLs.
Unit tests were extended to test a wider range of valid S3 URLs.
> Add support for virtual hosted style S3 URLs in String.asS3ObjectIdentifier()

- .github/workflows/swift.yml
- Package.resolved
- Package.swift
- README.md
- Sources/SmokeAWSHttp/AWSClientProtocol+asyncSupport.swift
- Sources/SmokeAWSHttp/AWSQueryClientProtocol+asyncSupport.swift
- Sources/SmokeAWSHttp/MockClientProtocol+asyncSupport.swift
- Sources/SmokeAWSHttp/MockThrowingClientProtocol+asyncSupport.swift
- docs/Support_Policy.md
1. Remove Swift 5.2 from CI tests
2. Update support document to indicate no support for Swift 5.2
3. Remove `@available` annotation from async APIs, increase the requirement for non Linux platforms to the upcoming 5.5.2 (which will backport async support to the earlier Apple OSs).
> Support async APIs on older Apple OSs.

- Sources/S3Client/S3Object.swift
- Sources/SmokeAWSMetrics/CloudWatchMetricsFactory.swift
- Sources/SmokeAWSMetrics/CloudWatchPendingMetricsQueue.swift
*Description of changes:* Add async shutdown methods for CloudWatchMetricsFactory and S3Object.
> Add async shutdown methods for CloudWatchMetricsFactory and S3Object.

- Sources/SmokeAWSCore/CloudwatchJsonStandardErrorLogger.swift
Add CloudwatchJsonStandardErrorLogger. This logger will emit log entries as JSON structures, taking the log message, metadata, file, line, level as separate entries.
> Add CloudwatchJsonStandardErrorLogger.

- Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
- Sources/SimpleNotificationClient/AWSSimpleNotificationClientGenerator.swift
- Sources/SmokeAWSHttp/FormEncodedXMLAWSHttpClientDelegate.swift
- Sources/SmokeAWSHttp/XMLAWSHttpClientDelegate.swift
Current SNS sends message payload in request query string. This has a limitation of 16KB.
This change adds a new XML encoder that puts a query string into request body.
This PR is meant to gather feedback. There are some TODO items remaining.
TODO:
* The generator is not updated to override content-type to `application/x-www-form-urlencoded; charset=utf-8`
* Added this functionality in this PR https://github.com/amzn/smoke-aws-generate/pull/59
* I tested SNS Publish and nothing else.
* I kept the change to SNS to limit the blast radius. However, I think SQS and other "query" services would have the same limitation. And may need the same solution. But it's a large scope. And I wanted to avoid that.
By submitting this pull request, I confirm that my contribution is made under the terms of …
> Support large SNS payloads

- Package.resolved
- Sources/SmokeAWSCore/CloudwatchJsonStandardErrorLogger.swift
- Sources/SmokeAWSCore/CloudwatchStandardErrorLogger.swift
- Sources/SmokeAWSCore/StdioOutputStream.swift
- Sources/SmokeAWSHttp/AWSClientInvocationDelegate.swift
- Sources/SmokeAWSHttp/AWSClientInvocationTraceContext.swift
- Sources/SmokeAWSHttp/DataAWSHttpClientDelegate.swift
- Sources/SmokeAWSHttp/HTTPClientDelegate+getErrorFromResponseAndBody.swift
- Sources/SmokeAWSHttp/JSONAWSHttpClientDelegate.swift
- Sources/SmokeAWSHttp/XMLAWSHttpClientDelegate.swift
1. Avoids potential interleaving of log messages from different threads. This uses the same file-locking mechanism as swift-log to achieve this
2. Reduce the severity of log messages emitted and structure logs messages using metadata. This will avoid emitting log when the level is debug or greater.
> Fix concurrency issue in the logger implementations.

- Sources/SmokeAWSCore/JSONDecoder+awsCompatibleEncoder.swift
Adds option to enable or disable pretty printing in the `awsCompatibleEncoder`. By default pretty printing will be enabled but this allows clients to disable pretty printing if needed (in the case of reducing JSON payload size).
> Add option to enable/disable pretty printing in awsCompatibleEncoder

- Sources/DynamoDBModel/DynamoDBModelStructures.swift
Make BatchStatementError Hashable. The db batch statement throws errors, the message and code is pair unique.. Make it hash-able to avoid duplication
> Make BatchStatementError hashable

- Package.resolved
- Package.swift
Swift 5.8 introduced compilation errors and warnings. Updating smoke-http to 2.19.1 fixes them.
> updated swift-http for swift 5.8

- Sources/S3Client/S3ClientProtocolV2+listFolder.swift
- Tests/S3ClientTests/S3ClientTests.swift
Add optional page size parameter to `ListFolder` utility function. When not provided, the page size will be the default for the `ListObjectsV2` operation - 1000 items.
> Add page size parameter to ListFolder

- Sources/ECRModel/ECRModelTypes.swift
*Description of changes:* Correct timestamp type for ECR models. Verified timestamps from the ECR service are returned as doubles rather than longs.
For example
```
imagePushedAt":1.688712875E9
```
> Correct timestamp type for ECR models.

- .github/workflows/codeql.yml
- .github/workflows/swift.yml
- Package.resolved
- Package.swift
- README.md
- Sources/AppConfigClient/AWSAppConfigClient.swift
- Sources/CloudWatchClient/AWSCloudWatchClient.swift
- Sources/CloudformationClient/AWSCloudformationClient.swift
- Sources/CodePipelineClient/AWSCodePipelineClient.swift
- Sources/DynamoDBClient/AWSDynamoDBClient.swift
- Sources/ECRClient/AWSECRClient.swift
- Sources/ElasticComputeCloudClient/AWSElasticComputeCloudClient.swift
- Sources/ElasticContainerClient/AWSElasticContainerClient.swift
- Sources/RDSClient/AWSRDSClient.swift
- Sources/RDSDataClient/AWSRDSDataClient.swift
- Sources/S3Client/AWSS3Client.swift
- Sources/SchedulerClient/AWSSchedulerClient.swift
- Sources/SecurityTokenClient/AWSSecurityTokenClient.swift
- Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
- Sources/SimpleQueueClient/AWSSimpleQueueClient.swift
- Sources/SimpleWorkflowClient/AWSSimpleWorkflowClient.swift
- Sources/StepFunctionsClient/AWSStepFunctionsClient.swift
- docs/Support_Policy.md
*Description of changes:* Use the AWSClientInvocationDelegate factory function for structured concurrency implementations. This will construct the AWSClientInvocationDelegate instance appropriately for the credentials provider instance passed, using credentials from the `CredentialsProviderV2` if available.
> Use AWSClientInvocationDelegate convenience function.

- Sources/CloudWatchClient/AWSCloudWatchClient.swift
- Sources/CloudWatchClient/AWSCloudWatchClientGenerator.swift
- Sources/CloudWatchModel/CloudWatchModelErrors.swift
This is a follow up to https://github.com/amzn/smoke-aws-generate/pull/98
> Update CloudWatch client to send payload in POST body instead of URL

- Package.resolved
- Package.swift
Update to use latest versions for dependencies. Follow up to https://github.com/amzn/smoke-http/pull/138 and https://github.com/amzn/smoke-aws-support/pull/20
> Update smoke http and smoke-aws-support major versions

- Sources/SimpleNotificationClient/AWSSimpleNotificationClient.swift
- Sources/SimpleNotificationModel/SimpleNotificationModelErrors.swift
SNS client does not recognize throttling error right now. This PR updates SNS client to do so.
```
unrecognizedError("Throttling", Optional("Rate exceeded")
```
Generator PR: https://github.com/amzn/smoke-aws-generate/pull/101
> Update SNS client to retry on Throttling error
